name: Testes do Pipeline

on: push

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Descarregar o código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install pandas pytest requests

      - name: Gerar dados brutos
        run: python extrair_dados.py

      - name: Transformar dados
        run: python transformar_dados.py

      - name: Correr os testes
        run: pytest test_dados.py -v